# JSON Exercise

In [62]:
# Importing necessary modules
import pandas as pd
import numpy as np
import json
from pandas.io.json import json_normalize

In [137]:
# Reading json file
json_a = pd.read_json('data/world_bank_projects.json')

In [138]:
# Shape of the dataframe
json_a.shape

(500, 50)

In [139]:
# Columns of the dataframe
json_a.columns

Index(['_id', 'approvalfy', 'board_approval_month', 'boardapprovaldate',
       'borrower', 'closingdate', 'country_namecode', 'countrycode',
       'countryname', 'countryshortname', 'docty', 'envassesmentcategorycode',
       'grantamt', 'ibrdcommamt', 'id', 'idacommamt', 'impagency',
       'lendinginstr', 'lendinginstrtype', 'lendprojectcost',
       'majorsector_percent', 'mjsector_namecode', 'mjtheme',
       'mjtheme_namecode', 'mjthemecode', 'prodline', 'prodlinetext',
       'productlinetype', 'project_abstract', 'project_name', 'projectdocs',
       'projectfinancialtype', 'projectstatusdisplay', 'regionname', 'sector',
       'sector1', 'sector2', 'sector3', 'sector4', 'sector_namecode',
       'sectorcode', 'source', 'status', 'supplementprojectflg', 'theme1',
       'theme_namecode', 'themecode', 'totalamt', 'totalcommamt', 'url'],
      dtype='object')

In [140]:
(json_a.head(3)).transpose()

,0,1,2
_id,{'$oid': '52b213b38594d8a2be17c780'},{'$oid': '52b213b38594d8a2be17c781'},{'$oid': '52b213b38594d8a2be17c782'}
approvalfy,1999,2015,2014
board_approval_month,November,November,November
boardapprovaldate,2013-11-12T00:00:00Z,2013-11-04T00:00:00Z,2013-11-01T00:00:00Z
borrower,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,GOVERNMENT OF TUNISIA,MINISTRY OF FINANCE AND ECONOMIC DEVEL
closingdate,2018-07-07T00:00:00Z,NaN,NaN
country_namecode,Federal Democratic Republic of Ethiopia!$!ET,Republic of Tunisia!$!TN,Tuvalu!$!TV
countrycode,ET,TN,TV
countryname,Federal Democratic Republic of Ethiopia,Republic of Tunisia,Tuvalu
countryshortname,Ethiopia,Tunisia,Tuvalu
docty,"Project Information Document,Indigenous People...","Project Information Document,Integrated Safegu...","Resettlement Plan,Environmental Assessment,Int..."
envassesmentcategorycode,C,C,B
grantamt,0,4700000,0
ibrdcommamt,0,0,0
id,P129828,P144674,P145310
idacommamt,130000000,0,6060000
impagency,MINISTRY OF EDUCATION,MINISTRY OF FINANCE,MINISTRY OF TRANSPORT AND COMMUNICATIONS
lendinginstr,Investment Project Financing,Specific Investment Loan,Investment Project Financing
lendinginstrtype,IN,IN,IN
lendprojectcost,550000000,5700000,6060000
majorsector_percent,"[{'Percent': 46, 'Name': 'Education'}, {'Perce...","[{'Percent': 70, 'Name': 'Public Administratio...","[{'Percent': 100, 'Name': 'Transportation'}]"
mjsector_namecode,"[{'code': 'EX', 'name': 'Education'}, {'code':...","[{'code': 'BX', 'name': 'Public Administration...","[{'code': 'TX', 'name': 'Transportation'}]"
mjtheme,[Human development],"[Economic management, Social protection and ri...","[Trade and integration, Public sector governan..."
mjtheme_namecode,"[{'code': '8', 'name': 'Human development'}, {...","[{'code': '1', 'name': 'Economic management'},...","[{'code': '5', 'name': 'Trade and integration'..."
mjthemecode,"8,11","1,6","5,2,11,6"
prodline,PE,RE,PE
prodlinetext,IBRD/IDA,Recipient Executed Activities,IBRD/IDA
productlinetype,L,L,L
project_abstract,{'cdata': 'The development objective of the Se...,NaN,NaN
project_name,Ethiopia General Education Quality Improvement...,TN: DTF Social Protection Reforms Support,Tuvalu Aviation Investment Project - Additiona...
projectdocs,"[{'DocDate': '28-AUG-2013', 'EntityID': '09022...","[{'DocDate': '29-MAR-2013', 'EntityID': '00033...","[{'DocDate': '21-OCT-2013', 'EntityID': '00033..."
projectfinancialtype,IDA,OTHER,IDA
projectstatusdisplay,Active,Active,Active
regionname,Africa,Middle East and North Africa,East Asia and Pacific
sector,"[{'Name': 'Primary education'}, {'Name': 'Seco...",[{'Name': 'Public administration- Other social...,[{'Name': 'Rural and Inter-Urban Roads and Hig...
sector1,"{'Percent': 46, 'Name': 'Primary education'}","{'Percent': 70, 'Name': 'Public administration...","{'Percent': 100, 'Name': 'Rural and Inter-Urba..."
sector2,"{'Percent': 26, 'Name': 'Secondary education'}","{'Percent': 30, 'Name': 'General public admini...",NaN
sector3,"{'Percent': 16, 'Name': 'Public administration...",NaN,NaN
sector4,"{'Percent': 12, 'Name': 'Tertiary education'}",NaN,NaN
sector_namecode,"[{'code': 'EP', 'name': 'Primary education'}, ...","[{'code': 'BS', 'name': 'Public administration...","[{'code': 'TI', 'name': 'Rural and Inter-Urban..."
sectorcode,"ET,BS,ES,EP","BZ,BS",TI
source,IBRD,IBRD,IBRD
status,Active,Active,Active
supplementprojectflg,N,N,Y
theme1,"{'Percent': 100, 'Name': 'Education for all'}","{'Percent': 30, 'Name': 'Other economic manage...","{'Percent': 46, 'Name': 'Regional integration'}"
theme_namecode,"[{'code': '65', 'name': 'Education for all'}]","[{'code': '24', 'name': 'Other economic manage...","[{'code': '47', 'name': 'Regional integration'..."
themecode,65,"54,24","52,81,25,47"
totalamt,130000000,0,6060000
totalcommamt,130000000,4700000,6060000
url,http://www.worldbank.org/projects/P129828/ethi...,http://www.worldbank.org/projects/P144674?lang=en,http://www.worldbank.org/projects/P145310?lang=en

## (a) Find the 10 countries with most projects

In [141]:
# Top 10 countries with most projects
# Creating a pivot table for existing dataframe -> Sorting the table in with respect to its counts -> Choosing top 10 values  
(pd.pivot_table(json_a, index = ['countryname'], values = ['project_name'], aggfunc = 'count')).sort_values('project_name', ascending=False).head(10)

                                 project_name
countryname
People's Republic of China                 19
Republic of Indonesia                      19
Socialist Republic of Vietnam              17
Republic of India                          16
Republic of Yemen                          13
People's Republic of Bangladesh            12
Nepal                                      12
Kingdom of Morocco                         12
Republic of Mozambique                     11
Africa                                     11

# (b) Find the top 10 major project themes

In [201]:
# Load 'json' file
json_b = json.load((open('data/world_bank_projects.json')))

In [202]:
# Normalizing 'json' with respect to the column 'mjtheme_namecode'
json_b_nrmlzd = json_normalize(json_b, 'mjtheme_namecode')

In [200]:
# Top 10 major project themes
# Pivoting the dataframe -> Sorting the records with respect to 'Code' -> Printing the top 10 values
(pd.pivot_table(json_b_nrmlzd, index = 'name', values = 'code', aggfunc='count')).sort_values('code', ascending=False).head(10)

                                              code
name
Environment and natural resources management   223
Rural development                              202
Human development                              197
Public sector governance                       184
Social protection and risk management          158
Financial and private sector development       130
                                               122
Social dev/gender/inclusion                    119
Trade and integration                           72
Urban development                               47

# (c) Create a dataframe with the missing names filled in.

In [204]:
# Load 'json' file
json_c = json.load((open('data/world_bank_projects.json')))

In [ ]:
# Normalizing json file with respect to the column 'mjtheme_namecode' 
json_c_nrmlzd = json_normalize(json_c, 'mjtheme_namecode')

In [190]:
# Sorting the normalized values by the columns 'code' and then 'name'  
json_c_nrmlzd = json_c_nrmlzd.sort_values(['code','name'])

In [191]:
# Filling the missing values with 'NaN'
json_c_nrmlzd.name[json_c_nrmlzd['name'] == ''] = np.nan

In [193]:
# Replace NaN with respective values using backward filling 
json_c_nrmlzd["name"].fillna(method='bfill', inplace=True)

## (c') updated dataframe with no missing values

In [195]:
# Updated dataframe and counts
json_c_nrmlzd.name.value_counts()

Environment and natural resources management    250
Rural development                               216
Human development                               210
Public sector governance                        199
Social protection and risk management           168
Financial and private sector development        146
Social dev/gender/inclusion                     130
Trade and integration                            77
Urban development                                50
Economic management                              38
Rule of law                                      15
Name: name, dtype: int64

In [196]:
# Top 10 project themes from updated dataframe.
(json_c_nrmlzd.name.value_counts()).head(10)

Environment and natural resources management    250
Rural development                               216
Human development                               210
Public sector governance                        199
Social protection and risk management           168
Financial and private sector development        146
Social dev/gender/inclusion                     130
Trade and integration                            77
Urban development                                50
Economic management                              38
Name: name, dtype: int64